### ISSUE TITLE
How about .xcassets file?

### ISSUE THREAD

**Issue by likeconan** [vital-edu/ios_flutter_plugin_with_native_assets#1]
I want to put all icons into xcassets like below:
<img width="737" alt="image" src="https://user-images.githubusercontent.com/12960160/191931686-7d97e460-1528-4817-8ee0-2f1f63f031e4.png">

The xcode now can see the assets like below:
<img width="796" alt="image" src="https://user-images.githubusercontent.com/12960160/191931857-d00bdb65-8a71-4af9-a90a-98f78e1bf51a.png">

May I ask how to use it as UIImage(named:"fullscreen_white").

Thanks a lot

**Comment by vital-edu** [comment]
@likeconan I hope you found the answer for your question. If you didn't, this is covered by the Flutter's documentation: https://docs.flutter.dev/development/ui/assets-and-images#loading-flutter-assets-in-ios.

**Comment by likeconan** [comment]
@vital-edu  Yes I did, thanks a lot again.
